### ISSUE TITLE
consola error when running

### ISSUE THREAD

**Issue by adrienbaron** [Developmint/nuxt-bundle-buddy#6]
When I try to run the build analyze, it crashes immediately with the following error:
```
× fatal file:///C:/Users/abaro/Git/cos-pwa/node_modules/nuxt-bundle-buddy/lib/module.js:1
  TypeError: consola.withTag is not a function
  at Object.<anonymous> (file:///C:/Users/abaro/Git/cos-pwa/node_modules/nuxt-bundle-buddy/lib/module.js:4:24)
  at Generator.next (<anonymous>)
```

Setup:
- Windows
- NPM 6.4.1
- Nuxt 2.2.0
- nuxt-bundle-buddy 0.0.1
- consola not setup on my own project

**Comment by manniL** [comment]
@adrienbaron Thanks for the detailed description!

The problem is that the first consola version used will take precedence (which is consola 1.x from `nuxt`). The project itself uses consola 2.x

There are a few solutions for this:

1. Upgrade to `nuxt-edge` (latest). No breaking changes and consola 2 support out of the box :+1: 

2. Use the `resolution` field to map all consola 1.x versions to consola 2 ([how to](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it))

**Comment by adrienbaron** [comment]
@manniL Thank you for the quick response! I just put this in my package.json:
```json
"resolutions": {
    "consola": "2.1.1"
  }
```
Then used `yarn` instead of `npm` and it works 👍 .
